package ec.gob.ambiente.api.reports;

public class KeysUtil {

	public String get(String key){
		switch(key){
			case "userId": return "UsuarioId";
			case "organizationManglarId": return "OrganizaciónId";
			case "officialDocsFormId": return "FormularioId";
			case "controlFormId": return "FormularioId";
			case "crabSizeFormId": return "FormularioId";
			case "deforestationFormId": return "FormularioId";
			case "descProjectsFormId": return "FormularioId";
			case "economicIndicatorsFormId": return "FormularioId";
			case "infoVedaFormId": return "FormularioId";
			case "investmentsOrgsFormId": return "FormularioId";
			case "planTrackingFormId": return "FormularioId";
			case "pricesFormId": return "FormularioId";
			case "reforestationFormId": return "FormularioId";
			case "shellSizeFormId": return "FormularioId";
			case "shellCollectionFormId": return "FormularioId";
			case "crabCollectionFormId": return "FormularioId";
			case "evidenceFormId": return "FormularioId";
			case "managementPlanFormId": return "FormularioId";
			case "socialIndicatorsFormId": return "FormularioId";
			case "technicalReportFormId": return "FormularioId";
			case "fishingEffortFormId": return "FormularioId";
			case "informationGathering": return "Levantamiento de información";
			case "eventType": return "Tipo de evento";
			case "mudaFeatures": return "Características de muda";
			case "observations": return "Observaciones";
			case "sizeForms": return "Talla";
			case "evidenceActivities": return "Evidencia";
			case "sectorName": return "Sector";
			case "activity": return "Actividad";
			case "activityDate": return "Fecha de actividad";
			case "activityDesc": return "Descripción actividad";
			case "activityResults": return "Observaciones";
			case "evidences": return "Evidencias";
			case "evidenceGroup": return "Evidencia";
			case "evidenceType": return "Tipo de evidencia";
			case "evidenceDoc": return "Evidencia del participante";
			case "dailyOffers": return "Ofertas diarias";
			case "dailyOffer": return "Oferta diaria";
			case "productType": return "Tipo producto";
			case "bioAquaticType": return "Tipo bioacuático";
			case "shellQuality": return "Calidad";
			case "shellCount": return "# conchas para venta";
			case "shellType": return "Tipo concha";
			case "shellPulpPounds": return "Lb pulpa de concha";
			case "crabQuality": return "Calidad";
			case "sartsCount": return "# sartas para venta";
			case "crabObservations": return "Observaciones";
			case "crabPulpPounds": return "Lb pulpa de cangrejo";
			case "mielMangleCount": return "# frascos para venta";
			case "otherProducts": return "Otros productos";
			case "bioAquaticPrice": return "Precio(USD)";
			case "otherProductsPrice": return "Precio(USD)";
			case "craftName": return "Nombre producto";
			case "craftCount": return "# productos";
			case "plantasMangleCount": return "# productos";
			case "serviceType": return "Tipo";
			case "bioemprendimientoName": return "Nombre bioemprendimiento";
			case "productImage": return "Foto";
			case "name": return "Nombre";
			case "mobile": return "Celular";
			case "projectType": return "Tipo";
			case "projectName": return "Nombre del proyecto";
			case "projectObjective": return "Objetivo del proyecto";
			case "institutionType": return "Tipo de institución";
			case "budget": return "Presupuesto asignado(USD)";
			case "institutionsName": return "Nombre de la insitución o instituciones";
			case "documents": return "Documentos";
			case "documentInfo": return "Documento";
			case "document": return "Documento";
			case "supportType": return "Tipo de apoyo";
			case "surveillanceControl": return "Control y vigilancia";
			case "sustainableUse": return "Uso sustentable";
			case "administrativesExpenses": return "Gastos administrativos";
			case "socialActivities": return "Actividades sociales";
			case "monitoring": return "Gestión y monitoreo";
			case "capacitation": return "Capacitación";
			case "reforestation": return "Reforestación";
			case "infrastructure": return "Infraestructura";
			case "principalActivity": return "Actividad principal";
			case "averageIncome": return "Ingreso promedio diario";
			case "alternativeActivities": return "Actividad secundaria";
			case "averageIncomeAlternatives": return "Ingreso promedio secundaria";
			case "useCustodyAgreement": return "Acuerdo de uso y custodia";
			case "organizationStatutes": return "Estatutos organización";
			case "internalRegulation": return "Reglamento interno";
			case "internalRegulationDate": return "Fecha aprobación reglamento";
			case "limitMapsCustody": return "Mapas limites bajo custodia";
			case "organizationName": return "Nombre organización";
			case "organizationLogo": return "Logo organización";
			case "summary": return "Resumen";
			case "organizationType": return "Tipo de organización";
			case "organizationLocation": return "Localización";
			case "yearCreation": return "Año de creación";
			case "sepsRegister": return "Registro en el SEPS";
			case "directorsRegister": return "Registro de directiva";
			case "directorsRegisterDate": return "Fecha aprobación registro directiva";
			case "legalExistence": return "Comprobante existencia legal";
			case "partnersDirectorsList": return "Listado socios";
			case "partnersListDate": return "Fecha aprobación listado";
			case "presidentName": return "Nombre";
			case "pin": return "Cédula";
			case "phone": return "Celular";
			case "email": return "Correo";
			case "agreements": return "Convenios";
			case "agreementInfo": return "Convenio";
			case "agreementType": return "Tipo de convenio";
			case "agreement": return "Convenio";
			case "startAgreementDate": return "Fecha desde";
			case "endAgreementDate": return "Fecha hasta";
			case "cumpleReglaNoEnajenar": return "¿La organización cumple con la regla de no vender, renunciar o dividir el área bajo custodia?";
			case "cumpleReglaNoEnajenarEvidencia": return "Evidencia";
			case "cumpleReglaNoAmpliar": return "¿La organización cumple con la regla de no ampliar el área de la custodia?";
			case "cumpleReglaNoAmpliarEvidencia": return "Evidencia";
			case "cumpleReglaBuenaVecindad": return "¿Las organizaciones firmantes del acuerdo de buena vecindad respete las reglas establecidos en el acuerdo  case vecindad?";
			case "cumpleReglaBuenaVecindadEvidencia": return "Evidencia";
			case "pescadoresDeOtrasOrgs": return "¿Se han encontrado pescadores de otras organizaciones con acuerdo en su área bajo custodia?";
			case "pescadoresDeOtrasOrgsEvidencia": return "Evidencia";
			case "denuncioPescadoresNoAutorizados": return "¿Se ha puesto una denuncia por el ingreso no autorizado de pescadores que no son socios de  case al área bajo custodia?";
			case "denuncioPescadoresNoAutorizadosEvidencia": return "Evidencia";
			case "todosRecurosBioacuaticos": return "¿Todos los socios realizan la actividad extractiva de recursos bioacuáticos del manglar?";
			case "todosRecurosBioacuaticosEvidencia": return "Evidencia";
			case "pescaFueraDelManglar": return "¿Los socios de la organización realizan actividades de pesca por fuera del manglar custodiado?";
			case "pescaFueraDelManglarEvidencia": return "Evidencia";
			case "actividadesDeCria": return "¿La organización realizó actividades de Cría, engorde o cultivo?";
			case "actividadesDeCriaEvidencia": return "Evidencia";
			case "cumpleNormasCria": return "¿La organización cumple con la normativa ambiental para la cría, engorde o cultivo de especies bioacuáticos?";
			case "cumpleNormasCriaEvidencia": return "Evidencia";
			case "devuelveIndividuosDecomisados": return "¿Se devuelve los individuos decomisados por incumplimiento de normativa de pesca a espacios de cría   case ";
			case "devuelveIndividuosDecomisadosEvidencia": return "Evidencia";
			case "actividadesTurismo": return "¿La organización realizó actividades de turismo ecológico?";
			case "actividadesTurismoEvidencia": return "Evidencia";
			case "normativaTuristica": return "¿La organización cumple con la normativa turística?";
			case "normativaTuristicaEvidencia": return "Evidencia";
			case "actividadesEducacionAmbiental": return "¿La organización realizó o participó en actividades de Educación Ambiental?";
			case "actividadesEducacionAmbientalEvidencia": return "Evidencia";
			case "actividadesInvestigacion": return "¿La organización realizó o participó en actividades de investigación?";
			case "actividadesInvestigacionEvidencia": return "Evidencia";
			case "cuentaConPermisos": return "¿La investigación cuenta con los debidos permisos?";
			case "cuentaConPermisosEvidencia": return "Evidencia";
			case "evidencioMuerteArboles": return "¿Se evidenció muerte, enfermedad o alguna otra degradación de los árboles de manglar en el área bajo custodia?";
			case "evidencioMuerteArbolesEvidencia": return "Evidencia";
			case "evidencioMuerteBioacuaticos": return "¿Se evidenció muerte, enfermedad o alguna otra degradación de las especies bioacuáticos en el área  case custodia (conchas y cangrejos)?";
			case "evidencioMuerteBioacuaticosEvidencia": return "Evidencia";
			case "evidencioMuerteFlora": return "¿Se evidenció muerte, enfermedad o alguna otra degradación de otras especies de flora en el área bajo custodia?";
			case "evidencioMuerteFloraEvidencia": return "Evidencia";
			case "evidencioMuerteFauna": return "¿Se evidenció muerte, enfermedad o alguna otra degradación de otras especies de fauna en el área bajo custodia?";
			case "evidencioMuerteFaunaEvidencia": return "Evidencia";
			case "cambiosEnAgua": return "¿Se evidenció cambios en el color, olor o temperatura del agua?";
			case "cambiosEnAguaEvidencia": return "Evidencia";
			case "cambiosSuelo": return "¿Se evidenció cambios en el color, olor o textura del suelo del manglar?";
			case "cambiosSueloEvidencia": return "Evidencia";
			case "cambiosClima": return "¿Se evidenció anomalías en el clima como lluvias más fuertes que lo normal, épocas más secas que lo normal?";
			case "cambiosClimaEvidencia": return "Evidencia";
			case "cambiosTemperatura": return "¿Se evidenció anomalías en el clima como temperaturas más fríos o calientes que lo normal?";
			case "cambiosTemperaturaEvidencia": return "Evidencia";
			case "pannedActivities": return "Actividades planificadas";
			case "plannedActivity": return "Actividad";
			case "activityDescription": return "Actividad";
			case "averageDone": return "% de cumplimiento";
			case "activityEvidence": return "Evidencia actividad";
			case "probableCause": return "Causa probable";
			case "deforestedArea": return "Área deforestada";
			case "custodyArea": return "Área custodia";
			case "protectedArea": return "Área protegida";
			case "location": return "Ubicación";
			case "latlong": return "Lat/Long";
			case "address": return "Dirección";
			case "estuary": return "Estuario";
			case "community": return "Comunidad";
			case "reforestedArea": return "Área reforestada(ha)";
			case "mangleSembradoCount": return "# mangle sembrados";
			case "plantingDate": return "Fecha de la siembra";
			case "plantingState": return "Estado de siembra";
			case "averageState": return "Porcentaje";
			case "entities": return "Entidades que brindaron apoyo";
			case "entityName": return "Nombre de la entidad";
			case "vertices": return "Puntos GPS de los vértices";
			case "vertice": return "Vértice";
			case "programs": return "Programas del plan de manejo";
			case "programsGroup": return "Información Programa";
			case "program": return "Programa";
			case "objectives": return "Objetivos del programa";
			case "objectivesGroup": return "Información Objetivo";
			case "objective": return "Objetivo";
			case "activities": return "Actividades del programa";
			case "activitiesGroup": return "Información Actividad";
			case "responsiblePatrullaje": return "Responsable del patrullaje";
			case "sector": return "Sector";
			case "startSite": return "Sitio de salida";
			case "endSite": return "Sitio de llegada";
			case "route": return "Recorrido";
			case "registerDetails": return "Detalles en registro";
			case "routeDuration": return "Duración del recorrido (min)";
			case "routeDate": return "Fecha";
			case "routeLocalities": return "Lugares recorridos";
			case "internalAuditor": return "Auditor interno";
			case "eventExists": return "¿Alguna novedad durante el patrullaje?";
			case "type": return "Tipo de novedad";
			case "verification": return "Medio de verificación";
			case "fishingEffortDate": return "Fecha";
			case "activePartners": return "Número socios activos";
			case "shellPeriod": return "Periodo";
			case "hoursWorked": return "# horas trabajadas";
			case "tuberculosasShellsCount": return "# conchas A. Tuberculosa";
			case "similisShellsCount": return "# conchas A. Similis";
			case "collectorName": return "Nombre recolector";
			case "collectorDate": return "Fecha de recolección";
			case "crabPeriod": return "Periodo";
			case "crabCollectedCount": return "# cangrejos recolectados";
			case "quedadosCrabs": return "# cangrejos quedados";
			case "femalesReturned": return "# hembras devueltas";
			case "collectedGreaterCount": return "# recolectados mayor a 7.5cm";
			case "concheroName": return "Nombre del conchero";
			case "samplingDate": return "Fecha de muestreo";
			case "shellSizes": return "Tallas conchas recolectadas";
			case "sizeGroup": return "Talla";
			case "cangrejeroName": return "Nombre del cangrejero";
			case "crabCount": return "# total cangrejos capturados";
			case "crabSizes": return "Tallas cangrejos recolectados";
			case "width": return "Ancho";
			case "length": return "Largo";
			case "sex": return "Sexo";
			case "countFamilyMembers": return "# miembros en familia";
			case "countManglarDependents": return "# dependientes manglar";
			case "incomePercentage": return "% ingresos act. en manglar $";
			case "nivel": return "Nivel educación";
		}
		return key;
	}


}
